/**
 * External dependencies
 */
import { __ } from '@wordpress/i18n';

const countryAmount = [
	[ __( 'Algeria', 'google-listings-and-ads' ), '45 USD' ],
	[ __( 'Argentina', 'google-listings-and-ads' ), '2300 ARS' ],
	[ __( 'Australia', 'google-listings-and-ads' ), '150 AUD' ],
	[ __( 'Austria', 'google-listings-and-ads' ), '120 EUR' ],
	[ __( 'Bahrain', 'google-listings-and-ads' ), '120 USD' ],
	[ __( 'Belarus', 'google-listings-and-ads' ), '90 USD' ],
	[ __( 'Belgium', 'google-listings-and-ads' ), '120 EUR' ],
	[ __( 'Bolivia', 'google-listings-and-ads' ), '75 USD' ],
	[ __( 'Bosnia and Herzegovina', 'google-listings-and-ads' ), '45 EUR' ],
	[ __( 'Brazil', 'google-listings-and-ads' ), '225 BRL' ],

	[ __( 'Bulgaria', 'google-listings-and-ads' ), '135 BGN' ],
	[ __( 'Canada', 'google-listings-and-ads' ), '150 CAD' ],
	[ __( 'Chile', 'google-listings-and-ads' ), '75 USD' ],
	[ __( 'Colombia', 'google-listings-and-ads' ), '75 USD' ],
	[ __( 'Costa Rica', 'google-listings-and-ads' ), '75 USD' ],
	[ __( 'Croatia', 'google-listings-and-ads' ), '600 HRK' ],
	[ __( 'Cyprus', 'google-listings-and-ads' ), '120 EUR' ],
	[ __( 'Czech Republic', 'google-listings-and-ads' ), '1500 CZK' ],
	[ __( 'Denmark', 'google-listings-and-ads' ), '900 DKK' ],
	[ __( 'Dominican Republic', 'google-listings-and-ads' ), '75 USD' ],

	[ __( 'Ecuador', 'google-listings-and-ads' ), '75 USD' ],
	[ __( 'Egypt', 'google-listings-and-ads' ), '225 EGP' ],
	[ __( 'El Salvador', 'google-listings-and-ads' ), '75 USD' ],
	[ __( 'Estonia', 'google-listings-and-ads' ), '60 EUR' ],
	[ __( 'Finland', 'google-listings-and-ads' ), '120 EUR' ],
	[ __( 'France', 'google-listings-and-ads' ), '120 EUR' ],
	[ __( 'Germany', 'google-listings-and-ads' ), '120 EUR' ],
	[ __( 'Greece', 'google-listings-and-ads' ), '120 EUR' ],
	[ __( 'Guatemala', 'google-listings-and-ads' ), '75 USD' ],
	[ __( 'Honduras', 'google-listings-and-ads' ), '75 USD' ],

	[ __( 'Hong Kong', 'google-listings-and-ads' ), '600 HKD' ],
	[ __( 'Hungary', 'google-listings-and-ads' ), '22500 HUF' ],
	[ __( 'Iceland', 'google-listings-and-ads' ), '120 EUR   ' ],
	[ __( 'India', 'google-listings-and-ads' ), '3000 INR' ],
	[ __( 'Indonesia', 'google-listings-and-ads' ), '675000 IDR' ],
	[ __( 'Ireland', 'google-listings-and-ads' ), '120 EUR' ],
	[ __( 'Israel', 'google-listings-and-ads' ), '450 ILS' ],
	[ __( 'Italy', 'google-listings-and-ads' ), '120 EUR' ],
	[ __( 'Japan', 'google-listings-and-ads' ), '11250 JPY' ],
	[ __( 'Jordan', 'google-listings-and-ads' ), '120 USD' ],

	[ __( 'Kazakhstan', 'google-listings-and-ads' ), '90 USD' ],
	[ __( 'Kenya', 'google-listings-and-ads' ), '50 USD' ],
	[ __( 'Korea', 'google-listings-and-ads' ), '150000 KRW' ],
	[ __( 'Kuwait', 'google-listings-and-ads' ), '120 USD' ],
	[ __( 'Latvia', 'google-listings-and-ads' ), '60 EUR' ],
	[ __( 'Lebanon', 'google-listings-and-ads' ), '120 USD' ],
	[ __( 'Libya', 'google-listings-and-ads' ), '45 USD' ],
	[ __( 'Lithuania', 'google-listings-and-ads' ), '60 EUR' ],
	[ __( 'Luxembourg', 'google-listings-and-ads' ), '120 EUR' ],
	[ __( 'Macedonia', 'google-listings-and-ads' ), '45 USD' ],

	[ __( 'Malaysia', 'google-listings-and-ads' ), '225 MYR' ],
	[ __( 'Malta', 'google-listings-and-ads' ), '120 EUR' ],
	[ __( 'Mexico', 'google-listings-and-ads' ), '1350 MXN' ],
	[ __( 'Montenegro', 'google-listings-and-ads' ), '60 EUR' ],
	[ __( 'Morocco', 'google-listings-and-ads' ), '45 USD' ],
	[ __( 'Netherlands', 'google-listings-and-ads' ), '120 EUR' ],
	[ __( 'New Zealand', 'google-listings-and-ads' ), '150 NZD' ],
	[ __( 'Nicaragua', 'google-listings-and-ads' ), '75 USD' ],
	[ __( 'Nigeria', 'google-listings-and-ads' ), '45 USD' ],
	[ __( 'Norway', 'google-listings-and-ads' ), '1125 NOK' ],

	[ __( 'Oman', 'google-listings-and-ads' ), '120 USD' ],
	[ __( 'Pakistan', 'google-listings-and-ads' ), '70 USD' ],
	[ __( 'Palestine', 'google-listings-and-ads' ), '120 USD' ],
	[ __( 'Panama', 'google-listings-and-ads' ), '75 USD' ],
	[ __( 'Paraguay', 'google-listings-and-ads' ), '75 USD' ],
	[ __( 'Peru', 'google-listings-and-ads' ), '75 USD' ],
	[ __( 'Philippines', 'google-listings-and-ads' ), '3000 PHP' ],
	[ __( 'Poland', 'google-listings-and-ads' ), '375 PLN' ],
	[ __( 'Portugal', 'google-listings-and-ads' ), '120 EUR' ],
	[ __( 'Puerto Rico', 'google-listings-and-ads' ), '75 USD' ],

	[ __( 'Qatar', 'google-listings-and-ads' ), '120 USD' ],
	[ __( 'Romania', 'google-listings-and-ads' ), '300 RON' ],
	[ __( 'Russia', 'google-listings-and-ads' ), '3000 RUB' ],
	[ __( 'Saudi Arabia', 'google-listings-and-ads' ), '450 SAR' ],
	[ __( 'Serbia', 'google-listings-and-ads' ), '60 EUR' ],
	[ __( 'Singapore', 'google-listings-and-ads' ), '120 SGD' ],
	[ __( 'Slovakia', 'google-listings-and-ads' ), '120 EUR' ],
	[ __( 'Slovenia', 'google-listings-and-ads' ), '120 EUR' ],
	[ __( 'South Africa', 'google-listings-and-ads' ), '900 ZAR' ],
	[ __( 'Spain', 'google-listings-and-ads' ), '120 EUR' ],

	[ __( 'Sri Lanka', 'google-listings-and-ads' ), '70 USD' ],
	[ __( 'Sweden', 'google-listings-and-ads' ), '1125 SEK' ],
	[ __( 'Switzerland', 'google-listings-and-ads' ), '150 CHF' ],
	[ __( 'Taiwan', 'google-listings-and-ads' ), '2250 TWD' ],
	[ __( 'Thailand', 'google-listings-and-ads' ), '2250 THB' ],
	[ __( 'Tunisia', 'google-listings-and-ads' ), '45 USD' ],
	[ __( 'Turkey', 'google-listings-and-ads' ), '150 TRY' ],
	[ __( 'Ukraine', 'google-listings-and-ads' ), '2000 UAH' ],
	[ __( 'United Arab Emirates', 'google-listings-and-ads' ), '450 AED' ],
	[ __( 'United Kingdom', 'google-listings-and-ads' ), '120 GBP' ],

	[ __( 'United States', 'google-listings-and-ads' ), '150 USD' ],
	[ __( 'Uruguay', 'google-listings-and-ads' ), '75 USD' ],
	[ __( 'Venezuela', 'google-listings-and-ads' ), '75 USD' ],
	[ __( 'Vietnam', 'google-listings-and-ads' ), '1350000 VND' ],
];

export default countryAmount;
