name: Set PR Labels

on:
  pull_request_target:
    types: opened

jobs:
  SetLabels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set Labels
        uses: woocommerce/grow/branch-label@68794d4270fbfb19bb0bb76d6cebc8dd18f7d133 # actions-v2
