name: Deploy Product

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., 3.5.0)'
        required: true
        type: string
      deploy_wporg:
        description: 'Deploy to WordPress.org'
        required: false
        default: true
        type: boolean
      deploy_github:
        description: 'Deploy to GitHub'
        required: false
        default: true
        type: boolean
      simulate:
        description: 'Dry run mode'
        required: false
        default: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      # Checkout the private action repository
      - name: Checkout woo-product-deploy action
        uses: actions/checkout@v4
        with:
          repository: woocommerce/woo-product-deploy
          ref: trunk
          path: ./.github/actions/woo-product-deploy
          token: ${{ secrets.ORG_DEPLOY_SECRET }}  # Need PAT with access to the action repository

      # Use the action we checked out
      - name: Deploy Product
        uses: ./.github/actions/woo-product-deploy
        with:
          repo_url: https://github.com/woocommerce/google-listings-and-ads
          branch: ${{ github.ref_name }}
          version: ${{ github.event.inputs.version }}
          node_version: '20'
          npm_version: '10'
          simulate: ${{ github.event.inputs.simulate }}
          github_release: ${{ github.event.inputs.deploy_github }}
          wporg_release: ${{ github.event.inputs.deploy_wporg }}
          wporg_username: ${{ secrets.WPORG_USERNAME }}
          wporg_password: ${{ secrets.WPORG_PASSWORD }}
          deploy_pat: ${{ secrets.ORG_DEPLOY_SECRET }}
          partner_user: ${{ secrets.ORG_PARTNER_USER }}
          partner_secret: ${{ secrets.ORG_PARTNER_DEPLOY_SECRET }}

      - name: Copy build zip and preview changes
        run: |
          TEMP_DIR=$(php -r 'echo sys_get_temp_dir();')
          SIMULATE=${{ github.event.inputs.simulate }}

          cd "$TEMP_DIR/google-listings-and-ads"
          cp google-listings-and-ads.zip ${{ github.workspace }}

          # Show git diff if it's a dry run
          if [ "$SIMULATE" == "true" ]; then
            git --no-pager diff
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: google-listings-and-ads.zip
          path: ${{ github.workspace }}/google-listings-and-ads.zip
          retention-days: 1
