name: JavaScript and CSS Linting

on:
  push:
    branches:
      - trunk
      - develop
    paths:
      - "**.js"
      - "**.scss"
      - .github/workflows/js-css-linting.yml
  pull_request:
    paths:
      - "**.js"
      - "**.scss"
      - .github/workflows/js-css-linting.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 2

jobs:
  JSLintingCheck:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@a81d3fca0166a02a4c25953d250d80d3612db4b8 # actions-v3
        with:
          node-version-file: ".nvmrc"

      - name: Prepare annotation formatter
        uses: woocommerce/grow/eslint-annotation@68794d4270fbfb19bb0bb76d6cebc8dd18f7d133 # actions-v2

      - name: Lint JavaScript and annotate linting errors
        run: npm run lint:js -- --quiet --format ./eslintFormatter.cjs

  CSSLintingCheck:
    name: Lint CSS
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@a81d3fca0166a02a4c25953d250d80d3612db4b8 # actions-v3
        with:
          node-version-file: ".nvmrc"

      - name: Prepare annotation formatter
        uses: woocommerce/grow/stylelint-annotation@68794d4270fbfb19bb0bb76d6cebc8dd18f7d133 # actions-v2

      - name: Lint CSS and annotate linting errors
        run: npm run lint:css -- --custom-formatter ./stylelintFormatter.cjs
