name: JavaScript and CSS Linting

on:
  push:
    branches:
      - trunk
      - develop
    paths:
      - "**.js"
      - "**.scss"
      - .github/workflows/js-css-linting.yml
  pull_request:
    paths:
      - "**.js"
      - "**.scss"
      - .github/workflows/js-css-linting.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 2

jobs:
  JSLintingCheck:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@b9c1e59aae9fdbe668b068ebd59c1545a88ea9fa # actions-v3.0.5
        with:
          node-version-file: ".nvmrc"

      - name: Prepare annotation formatter
        uses: woocommerce/grow/eslint-annotation@68794d4270fbfb19bb0bb76d6cebc8dd18f7d133 # actions-v2

      - name: Lint JavaScript and annotate linting errors
        run: npm run lint:js -- --quiet --format ./eslintFormatter.cjs

  CSSLintingCheck:
    name: Lint CSS
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@b9c1e59aae9fdbe668b068ebd59c1545a88ea9fa # actions-v3.0.5
        with:
          node-version-file: ".nvmrc"

      - name: Prepare annotation formatter
        uses: woocommerce/grow/stylelint-annotation@68794d4270fbfb19bb0bb76d6cebc8dd18f7d133 # actions-v2

      - name: Lint CSS and annotate linting errors
        run: npm run lint:css -- --custom-formatter ./stylelintFormatter.cjs
