name: PHP Coding Standards

on:
  push:
    branches:
      - trunk
      - develop
    paths:
      - "**.php"
      - composer.json
      - composer.lock
      - .github/workflows/php-coding-standards.yml
  pull_request:
    paths:
      - "**.php"
      - composer.json
      - composer.lock
      - .github/workflows/php-coding-standards.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: PHP coding standards
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Prepare PHP
        uses: woocommerce/grow/prepare-php@b9c1e59aae9fdbe668b068ebd59c1545a88ea9fa # actions-v3.0.5
        with:
          tools: cs2pr

      - name: Log PHPCS information
        run: vendor/bin/phpcs -i

      - name: Run PHPCS on all files
        run: vendor/bin/phpcs ./* -q --report=checkstyle | cs2pr

      - name: Run PHPCS on all tests
        run: vendor/bin/phpcs -q --standard=tests/phpcs.xml.dist --report=checkstyle | cs2pr
