name: Deploy Storybook

on:
  push:
    branches:
      - trunk
      - develop
    paths:
      -  "./js/src/components/**"
      - ./package.json
      - ./package-lock.json
      - "./storybook/**"
      - ./.github/workflows/storybook-workflow.yml
      - ./.github/actions/prepare-node/action.yml
  pull_request:
    paths:
      - "./js/src/components/**"
      - ./package.json
      - ./package-lock.json
      - "./storybook/**"
      - ./.github/workflows/storybook-workflow.yml
      - ./.github/actions/prepare-node/action.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare node
        uses: ./.github/actions/prepare-node

      - name: Deploy Storybook
        run: npm run storybook:deploy
